/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tlvzfmdU6Cl
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import Image from "next/image";
import { SwipeCarousel } from "./carousel";

export function Landing() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="text-2xl font-bold">IEEE Student Branch</div>
        <nav className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Team
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Events
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Gallery
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        {/* <section className="flex justify-center items-center"> */}
        <SwipeCarousel />
        {/* </section> */}
        <section
          id="about"
          className="flex justify-center items-center w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  About the IEEE Student Branch
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  The IEEE Student Branch is a vibrant community of engineering
                  students dedicated to exploring the latest advancements in
                  technology, fostering innovation, and connecting with industry
                  professionals. Our mission is to provide a platform for
                  students to develop their technical skills, engage in hands-on
                  projects, and collaborate with like-minded individuals.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          id="counselor"
          className="flex justify-center items-center w-full py-12 md:py-24 lg:py-32"
        >
          <div className="container px-4 md:px-6">
            <div className="mx-auto grid max-w-5xl items-center gap-6 lg:grid-cols-2 lg:gap-12">
              <Image
                // src="https://ieeestb.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FZaid-sir.22016aa3.png&w=750&q=75"
                src={
                  "https://ieeestb.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FZaid-sir.22016aa3.png&w=750&q=75"
                }
                width={1080}
                height={1080}
                alt="Branch Counselor"
                className="mx-auto aspect-square overflow-hidden rounded-full object-cover object-center sm:w-full lg:order-last md:p-16 p-8"
              />
              <div className="flex flex-col justify-center space-y-4">
                <h3 className="text-3xl flex font-bold tracking-tighter">
                  Message from the Branch Counselor
                </h3>
                <p className="text-muted-foreground">
                  I am glad to pen for the IEEE Student Branch of Zakir Hussain
                  College of Engineering and Technology, AMU. IEEE is the
                  world&apos;s largest technical professional organization
                  dedicated to advancing technology for the benefit of humanity.
                </p>
                <p className="text-muted-foreground">
                  The student branch in collaboration with other affinity
                  groups, has been organizing several tech conferences,
                  competitions, workshops, and seminars. The newsletter
                  highlights the various events, awards, and recognitions that
                  took place, thus making it a rewarding experience for the
                  readers.
                </p>
                <p className="text-muted-foreground">
                  I congratulate the chairs, office bearers, and volunteers who
                  have given their utmost dedication, time, and expertise in
                  maintaining one of the most vibrant and outshining clubs at
                  AMU.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          id="societies"
          className="flex justify-center items-center w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  IEEE Sub-Societies
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore the diverse range of sub-societies within the IEEE
                  Student Branch, each catering to specific areas of interest
                  and providing unique opportunities for growth and development.
                </p>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 mt-12">
              <div className="flex flex-col items-center justify-center space-y-4">
                <Image
                  src="https://ieeestb.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fcomputer-society.1f6c3046.webp&w=256&q=75"
                  width="80"
                  height="80"
                  alt="IEEE Computer Society"
                  className="aspect-square object-contain"
                />
                <div className="text-center">
                  <h3 className="text-lg font-bold">IEEE Computer Society</h3>
                  <p className="text-muted-foreground">
                    The IEEE Computer Society is the world&apos;s leading
                    membership organization dedicated to computer science and
                    technology. A global leader in providing access to computer
                    science research, analysis, and information.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center space-y-4">
                <Image
                  src="https://ieeestb.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FWIE.0cc72f01.png&w=256&q=75"
                  width="80"
                  height="80"
                  alt="IEEE WIE"
                  className="aspect-square object-contain"
                />
                <div className="text-center">
                  <h3 className="text-lg font-bold">IEEE WIE</h3>
                  <p className="text-muted-foreground">
                    IEEE Aligarh Muslim University (AMU), Women in Engineering
                    (WIE) Affinity Group, established in 2019 under the guidance
                    of honorable founding faculty advisor Ms. Qurratulain IEEE
                    AMU and respectable Chairperson Ms. Mahena Mahmood.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center space-y-4">
                <Image
                  src="https://ieeestb.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FRAS.60f7831d.webp&w=256&q=75"
                  width="80"
                  height="80"
                  alt="IEEE RAS"
                  className="aspect-square object-contain"
                />
                <div className="text-center">
                  <h3 className="text-lg font-bold">IEEE RAS</h3>
                  <p className="text-muted-foreground">
                    IEEE-RAS ZHCET is directly affiliated with the collegiate
                    IEEE Student Branch, ZHCET. Being a member of RAS provides
                    opportunities for collaboration and exchange of information
                    with peers, communication of the latest technological
                    developments, and career development possibilities.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center space-y-4">
                <Image
                  src="https://ieeestb.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FSight.2820b928.png&w=256&q=75"
                  width="80"
                  height="80"
                  alt="IEEE Sight"
                  className="aspect-square object-contain"
                />
                <div className="text-center">
                  <h3 className="text-lg font-bold">IEEE Sight</h3>
                  <p className="text-muted-foreground">
                    The Section undertook many events for approximately one
                    year, such as webinars, interactive workshops, etc. In all
                    the events, the main goal was to integrate the SIGHT motto
                    of sustainability intersection with technology.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section
          id="events"
          className="flex justify-center items-center w-full py-12 md:py-24 lg:py-32"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Upcoming Events
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out a preview of our upcoming events and join us to
                  explore the latest advancements in technology and connect with
                  industry professionals.
                </p>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-12">
              <div className="flex flex-col items-center justify-center space-y-4">
                <img
                  src="/placeholder.svg"
                  alt="IEEE Robotics Workshop"
                  className="aspect-[3/2] w-full object-cover rounded-lg"
                />
                <div className="text-center">
                  <h3 className="text-lg font-bold">IEEE Robotics Workshop</h3>
                  <p className="text-muted-foreground">
                    Explore the latest advancements in robotics and automation.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 mt-2 text-primary hover:underline"
                    prefetch={false}
                  >
                    Learn More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center space-y-4">
                <img
                  src="/placeholder.svg"
                  alt="IEEE Power & Energy Symposium"
                  className="aspect-[3/2] w-full object-cover rounded-lg"
                />
                <div className="text-center">
                  <h3 className="text-lg font-bold">
                    IEEE Power & Energy Symposium
                  </h3>
                  <p className="text-muted-foreground">
                    Explore the latest advancements in power generation and
                    energy systems.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 mt-2 text-primary hover:underline"
                    prefetch={false}
                  >
                    Learn More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center space-y-4">
                <img
                  src="/placeholder.svg"
                  alt="IEEE Computer Society Hackathon"
                  className="aspect-[3/2] w-full object-cover rounded-lg"
                />
                <div className="text-center">
                  <h3 className="text-lg font-bold">
                    IEEE Computer Society Hackathon
                  </h3>
                  <p className="text-muted-foreground">
                    Explore the latest advancements in computer science and
                    technology.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 mt-2 text-primary hover:underline"
                    prefetch={false}
                  >
                    Learn More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="flex justify-center mt-8">
              <Link
                href="#"
                className="inline-flex items-center gap-2 px-6 py-2 rounded-md bg-primary text-primary-foreground font-medium hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-ring"
                prefetch={false}
              >
                View All Events
                <ArrowRightIcon className="w-4 h-4" />
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex justify-center items-center bg-primary text-primary-foreground py-6 px-4 md:px-6">
        <div className="container flex flex-col md:flex-row items-center justify-between">
          <div className="flex items-center gap-2">
            <Image
              src="https://ieeestb.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fieee%20mb%20white%20png.801fb8eb.png&w=256&q=75"
              width="40"
              height="40"
              alt="IEEE Logo"
              className="aspect-square object-contain invert"
            />
            <span className="text-lg font-bold">IEEE Student Branch AMU</span>
          </div>
          <nav className="flex items-center gap-4 mt-4 md:mt-0">
            <Link href="#" className="hover:underline" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Team
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Events
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Gallery
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
        </div>
      </footer>
      <footer className="flex justify-center items-center bg-muted text-muted-foreground py-4 px-4 md:px-6">
        <div className="container flex flex-col md:flex-row items-center justify-between">
          <div className="flex items-center gap-4">
            <Link
              href="https://www.instagram.com/ieeeamu/"
              className="hover:underline"
              prefetch={false}
            >
              <InstagramIcon className="w-6 h-6" />
            </Link>
            <Link
              href="https://www.youtube.com/@ieeeamu720/featured"
              className="hover:underline"
              prefetch={false}
            >
              <YoutubeIcon className="w-6 h-6" />
            </Link>
            <Link
              href="https://www.facebook.com/IEEE.org/"
              className="hover:underline"
              prefetch={false}
            >
              <FacebookIcon className="w-6 h-6" />
            </Link>
            <Link
              href="https://www.linkedin.com/company/ieee-amu-student-branch/"
              className="hover:underline"
              prefetch={false}
            >
              <LinkedinIcon className="w-6 h-6" />
            </Link>
            <Link
              href="https://twitter.com/IEEEorg"
              className="hover:underline"
              prefetch={false}
            >
              <TwitterIcon className="w-6 h-6" />
            </Link>
          </div>
          <p className="text-sm mt-4 md:mt-0">
            &copy; 2024 IEEE Student Branch AMU. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}

function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}

function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  );
}
